In [2]:
from scipy import stats

# Stock return and market index return 
stock_returns = [0.065, 0.0265, -0.0593, -0.001, 0.0346]
mkt_returns = [0.055, -0.09, -0.041, 0.045, 0.022]

# CAPM
[beta, alpha, r_value, p_value, std_err] = stats.linregress(stock_returns, mkt_returns)
print('beta =',beta,', alpha =',alpha)

# Calculating the SML
rf = 0.05
mrisk_prem = 0.085

risk_prem = mrisk_prem*beta
expected_stock_return = rf + risk_prem
print('expected stock return:', expected_stock_return)

beta = 0.5077431878770808 , alpha = -0.008481900352462384
expected stock return: 0.09315817096955187


In [3]:
"""Linear Regression"""

import numpy as np
import statsmodels.api as sm
import random
random.seed(12345)

num_periods = 21
all_values = np.array([np.random.random(8) for i in range (num_periods)])
y_values = all_values[:,0]
x_values = all_values[:,1:]
x_values = sm.add_constant(x_values)   # Include the intercept
results = sm.OLS(y_values, x_values).fit()   # Regress and fit the model
print(results.summary())
print(results.params)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.539
Model:                            OLS   Adj. R-squared:                  0.291
Method:                 Least Squares   F-statistic:                     2.175
Date:                Sun, 29 Nov 2020   Prob (F-statistic):              0.107
Time:                        16:46:35   Log-Likelihood:                 4.6915
No. Observations:                  21   AIC:                             6.617
Df Residuals:                      13   BIC:                             14.97
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2196      0.248      0.885      0.3

In [4]:
"""Linear algebra with numpy matrices"""

import numpy as np


A = np.array([[10.,-1.,2.,0.], [-1.,11.,-1.,3.],
            [2.,-1.,10.,-1.], [0.0,3.,-1.,8.]])
B = np.array([6.,25.,-11.,15.])
print('The solution for Ax=B is x=', np.linalg.solve(A,B))

The solution for Ax=B is x= [ 1.  2. -1.  1.]


In [9]:
"""LU decomposition with Scipy"""

import scipy.linalg as linalg
import numpy as np


A = np.array([[10.,-1.,2.,0.], [-1.,11.,-1.,3.],
            [2.,-1.,10.,-1.], [0.0,3.,-1.,8.]])
B = np.array([6.,25.,-11.,15.])

LU = linalg.lu_factor(A)
x = linalg.lu_solve(LU,B)
P,L,U = linalg.lu(A)
print('L =',L,'\n')
print('U =',U,'\n')
print('The solution for Ax=B by LU decomposition is x=', x)

L = [[ 1.          0.          0.          0.        ]
 [-0.1         1.          0.          0.        ]
 [ 0.2        -0.0733945   1.          0.        ]
 [ 0.          0.27522936 -0.08173077  1.        ]] 

U = [[10.         -1.          2.          0.        ]
 [ 0.         10.9        -0.8         3.        ]
 [ 0.          0.          9.5412844  -0.77981651]
 [ 0.          0.          0.          7.11057692]] 

The solution for Ax=B by LU decomposition is x= [ 1.  2. -1.  1.]


In [10]:
"""Cholesky decomposition with Numpy"""

import numpy as np


A = np.array([[10.,-1.,2.,0.], [-1.,11.,-1.,3.],
            [2.,-1.,10.,-1.], [0.0,3.,-1.,8.]])
B = np.array([6.,25.,-11.,15.])
L = np.linalg.cholesky(A)
print('L =',L,'\n')

print('A =', np.dot(L,L.T.conj()),'\n')
y = np.linalg.solve(L,B)
x = np.linalg.solve(L.T.conj(),y)
print('Solution to Ax=B by Cholesky decomposition is x=', x)

L = [[ 3.16227766  0.          0.          0.        ]
 [-0.31622777  3.3015148   0.          0.        ]
 [ 0.63245553 -0.24231301  3.08889696  0.        ]
 [ 0.          0.9086738  -0.25245792  2.6665665 ]] 

A = [[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]] 

Solution to Ax=B by Cholesky decomposition is x= [ 1.  2. -1.  1.]


In [56]:
"""QR decomposition with scipy"""

import scipy.linalg as linalg
import numpy as np


A = np.array([[10.,-1.,2.,0.], [-1.,11.,-1.,3.],
            [2.,-1.,10.,-1.], [0.0,3.,-1.,8.]])
B = np.array([6.,25.,-11.,15.])
Q, R = linalg.qr(A)
y = np.dot(Q.T,B)
x = linalg.solve(R,y)
print('Solution to Ax=B by QR decomposition is x=', x)

Solution to Ax=B by QR decomposition is x= [ 1.  2. -1.  1.]


In [55]:
"""Solve Ax=B with the Jacobi method"""

import numpy as np


def jacobi(A, B, n, tol=1e-10):
    
   
    x = np.zeros_like(B)   #Initializes x with zeros with same shape and type as B
    for it_count in range(n):
        x_new = np.zeros_like(x)
        for i in range(A.shape[0]):
            s1 = np.dot(A[i,:i],x[:i])
            s2 = np.dot(A[i,i+1:],x[i+1:])
            x_new[i] = (B[i]-s1-s2)/A[i,i]
        if np.allclose(x,x_new,tol):
            break
        x = x_new
    return x

A = np.array([[10.,-1.,2.,0.], [-1.,11.,-1.,3.],
            [2.,-1.,10.,-1.], [0.0,3.,-1.,8.]])
B = np.array([6.,25.,-11.,15.])
n = 25
x = jacobi(A, B, n)
print("Solution to Ax=B by Jordan method is x=", x)

Solution to Ax=B by Jordan method is x= [ 1.  2. -1.  1.]


In [54]:
import numpy as np


def gauss(A, B, n, tol=1e-10):
    
    """ solves Ax=B with the Gauss-Seidel method"""
    
    L = np.tril(A)
    U = A - L   #decompose A=L+U
    L_inv = np.linalg.inv(L)
    x = np.zeros_like(B)
    
    for i in range(n):
        Ux = np.dot(U,x)
        x_new = np.dot(L_inv,B-Ux)

        if np.allclose(x,x_new,tol):
            break
        
        x = x_new
        
    return x

A = np.array([[10.,-1.,2.,0.], [-1.,11.,-1.,3.],
            [2.,-1.,10.,-1.], [0.0,3.,-1.,8.]])
B = np.array([6.,25.,-11.,15.])
n = 100
x = gauss(A, B, n)
print("Solution to Ax=B by Gauss-Seidel method is x=", x)    

Solution to Ax=B by Gauss-Seidel method is x= [ 1.  2. -1.  1.]
